### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by matfantinel** [matfantinel/reminduck#10]
Right now the app looks broken if "Prefer dark variant" in elementary-tweaks is checked. With the official dark mode coming sometime in the near future, this needs to be fixed.

It is mainly caused by absolute use of colors in some places - mainly in `.reminduck-welcome-box` and `.reminduck-reminders-list .list-item`. I suppose just finding out what's the right CSS flag for dark mode and selecting appropriate colors would be good enough to fix this.

Screenshots:

![image](https://user-images.githubusercontent.com/24247035/66486779-a4ea2580-ea81-11e9-88e8-cabbdea2f1c4.png)
![image](https://user-images.githubusercontent.com/24247035/66486819-b16e7e00-ea81-11e9-9823-9620c08eab40.png)

**Comment by alainm23** [comment]
To Header add:

`@define-color textColorPrimary @color_text;`
