### ISSUE TITLE
Color Banner in Appcenter is AWFUL

### ISSUE THREAD

**Issue by rasmus91** [matfantinel/reminduck#12]
Hi

I'm not sure if this is your decision, or something auto generated or whatever, but please get the banner color in the appcenter changed for this app:
It is basically unreadable, and hurts the eyes.

![billede](https://user-images.githubusercontent.com/2297739/66544515-afb3c180-eb38-11e9-819d-0c241e0443e8.png)

**Comment by matfantinel** [comment]
Oh, wow! That was a mistake.

Thanks for the report. This should be fixed soon.
