### ISSUE TITLE
Support for integrated timers till (from) date and time.

### ISSUE THREAD

**Issue by aatarasov** [matfantinel/reminduck#14]
I offer to add timer to every reminder.
Such timers allows to see the remaining and passed time at a quick glance.

Example:
![example](https://user-images.githubusercontent.com/54938560/66634365-575aed80-ec26-11e9-9cc5-4106dcafe1f7.png)

**Comment by matfantinel** [comment]
A small countdown until the reminder might actually be doable in the future. A countdown **from** it, though, is kinda outside the scope of this app, as it's not really a reminder.
