### ISSUE TITLE
App crashes when saving any reminder

### ISSUE THREAD

**Issue by javierfurus** [matfantinel/reminduck#19]
Hi!
I am in love with the app's simple design and premise. However, I could not test it out. I installed it through the AppCenter in eOS but whenever I save a reminder it crashes.

Here is the output of the command line mode, hope it helps:
ERROR:/build/com.github.matfantinel.reminduck-1.2.0/src/Database.vala:148:reminduck_database_upsert_reminder: assertion failed: (param_position > 0)

**Comment by matfantinel** [comment]
Oof, that's ugly.

That log helped a lot. I'm fixing it and will release very soon!

**Comment by matfantinel** [comment]
Hey @javierfurus , just letting you know that v1.2.1 was finally approved on AppCenter. `sudo apt update` will make it show up there in case it still hasn't. :)

**Comment by javierfurus** [comment]
![Screenshot from 2019-10-21 22-16-47](https://user-images.githubusercontent.com/14946527/67240293-73923200-f451-11e9-9fcf-7147aca7fede.png)

It is working, lovely! Thank you! :)
You are a wonderful developer! :)
