### ISSUE TITLE
Emoji won't show properly in notification bubble

### ISSUE THREAD

**Issue by DanyGee** [matfantinel/reminduck#38]
Here is the notification...
![Screenshot from 2020-01-11 16 34 31@2x](https://user-images.githubusercontent.com/26818551/72206635-abc57180-3490-11ea-870f-128180c8cb0e.png)

...and here is the bubble
![Screenshot from 2020-01-11 16 33 54@2x](https://user-images.githubusercontent.com/26818551/72206640-b97af700-3490-11ea-8b55-299558333763.png)
My machine
![image](https://user-images.githubusercontent.com/26818551/72206665-f5ae5780-3490-11ea-92c1-1b1660e7dc01.png)

**Comment by matfantinel** [comment]
Hey @DanyGee , thanks for reporting the issue.

However, I think this is an issue with Pantheon itself, since I've noticed other apps only show the emoji's "silhouette" on the bubbles as well. As the app, there's no difference between the bubble and notification list for me.
