### ISSUE TITLE
Reminduck doesn't save reminders after reboot

### ISSUE THREAD

**Issue by haunt98** [matfantinel/reminduck#52]
It occurs on my machine.
I use Archlinux with Gnome with reminduck install from flathub.
Everytime I reboot, reminders just disappear. Is this a bug or feature ?

**Comment by matfantinel** [comment]
Definitely a bug. Reminders should persist after reboots.

I will try to reproduce this locally when I can, in the meantime if you're familiar with it,  you can try compiling it from source to see if the issue still happens.

**Comment by internetman420** [comment]
Sorry to spam:

Is it neccesary to put reminduck as a login app to have it work after a reboot? does it work in the background even if you close the app?

**Comment by matfantinel** [comment]
@internetman420 nope, it writes the reminders to a local small database and should be able to access it anytime.

The app is supposed to stay running in the background after closed, but that behavior was only tested in elementary and Gnome.

Can you check if, after saving a reminder, you're able to see it inside the app? A new option should appear on the main screen that takes you to a list of your reminders

**Comment by internetman420** [comment]
Made a reminder yesterday. Shut down machine. Slept. Woke up, turn on, bang reminder shows up! Im on Elementary btw.
