### ISSUE TITLE
Marking the Project as Archived

### ISSUE THREAD

**Issue by yakushabb** [matfantinel/reminduck#66]
@matfantinel Could you please mark the project as archived?

> Unfortunately, I am not able to work on Reminduck anymore. It was a fun side project but I no longer use Linux and don't have the time to make sure it keeps working correctly.

If you mark the project as archived, I will create a PR to mark the application as EOL on the Flathub side.

**Comment by matfantinel** [comment]
@yakushabb will do! Hadn't thought of that.

I did the same for [Moneta](https://github.com/matfantinel/moneta).
